const createdByEmail = 'mando@signoz.io';

export const getAPIKeysResponse = {
	status: 'success',
	data: [
		{
			id: '26',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '',
				name: '',
				email: '',
				createdAt: 0,
				profilePictureURL: '',
				notFound: true,
			},
			token: '',
			role: 'ADMIN',
			name: '1 Day Old',
			createdAt: 1708010258,
			expiresAt: 1708096658,
			updatedAt: 1708010258,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: '',
		},
		{
			id: '24',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			token: '',
			role: 'ADMIN',
			name: '1 year expiry - updated',
			createdAt: 1708008146,
			expiresAt: 1739544146,
			updatedAt: 1708008239,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: 'mandalorian',
		},
		{
			id: '25',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			token: '',
			role: 'ADMIN',
			name: 'No Expiry Token',
			createdAt: 1708008178,
			expiresAt: 0,
			updatedAt: 1708008190,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: 'mandalorian',
		},
		{
			id: '22',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			token: '',
			role: 'VIEWER',
			name: 'No Expiry',
			createdAt: 1708007395,
			expiresAt: 0,
			updatedAt: 1708007936,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: 'mandalorian',
		},
		{
			id: '23',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			token: '',
			role: 'VIEWER',
			name: 'No Expiry - 2',
			createdAt: 1708007685,
			expiresAt: 0,
			updatedAt: 1708007786,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: 'mandalorian',
		},
		{
			id: '19',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			token: '',
			role: 'ADMIN',
			name: '7 Days',
			createdAt: 1708003326,
			expiresAt: 1708608126,
			updatedAt: 1708007380,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: 'mandalorian',
		},
		{
			id: '20',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			token: '',
			role: 'EDITOR',
			name: '1 month',
			createdAt: 1708004012,
			expiresAt: 1710596012,
			updatedAt: 1708005206,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: 'mandalorian',
		},
		{
			id: '21',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			token: '',
			role: 'ADMIN',
			name: '3 Months',
			createdAt: 1708004755,
			expiresAt: 1715780755,
			updatedAt: 1708005197,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: 'mandalorian',
		},
		{
			id: '17',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '',
				name: '',
				email: '',
				createdAt: 0,
				profilePictureURL: '',
				notFound: true,
			},
			token: '',
			role: 'ADMIN',
			name: 'New No Expiry',
			createdAt: 1708000444,
			expiresAt: 0,
			updatedAt: 1708000444,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: '',
		},
		{
			id: '14',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '',
				name: '',
				email: '',
				createdAt: 0,
				profilePictureURL: '',
				notFound: true,
			},
			token: '',
			role: 'EDITOR',
			name: 'Editor Token for user 1',
			createdAt: 1707997720,
			expiresAt: 1708170520,
			updatedAt: 1707997720,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: '',
		},
		{
			id: '13',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '',
				name: '',
				email: '',
				createdAt: 0,
				profilePictureURL: '',
				notFound: true,
			},
			token: '',
			role: 'EDITOR',
			name: 'Editor Token for user 2',
			createdAt: 1707997603,
			expiresAt: 1708170403,
			updatedAt: 1707997603,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: '',
		},
		{
			id: '12',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '',
				name: '',
				email: '',
				createdAt: 0,
				profilePictureURL: '',
				notFound: true,
			},
			token: '',
			role: 'EDITOR',
			name: 'Editor Token for user 3',
			createdAt: 1707997539,
			expiresAt: 1708170339,
			updatedAt: 1707997539,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: '',
		},
		{
			id: '11',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '',
				name: '',
				email: '',
				createdAt: 0,
				profilePictureURL: '',
				notFound: true,
			},
			token: '',
			role: 'EDITOR',
			name: 'Editor Token for user',
			createdAt: 1707997537,
			expiresAt: 1708170337,
			updatedAt: 1707997537,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: '',
		},
		{
			id: '10',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '',
				name: '',
				email: '',
				createdAt: 0,
				profilePictureURL: '',
				notFound: true,
			},
			token: '',
			role: 'EDITOR',
			name: 'test123',
			createdAt: 1707997288,
			expiresAt: 1708083688,
			updatedAt: 1707997288,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: '',
		},
		{
			id: '9',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '',
				name: '',
				email: '',
				createdAt: 0,
				profilePictureURL: '',
				notFound: true,
			},
			token: '',
			role: 'VIEWER',
			name: 'Viewer Token for user',
			createdAt: 1707996747,
			expiresAt: 1708255947,
			updatedAt: 1707996747,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: '',
		},
		{
			id: '8',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '',
				name: '',
				email: '',
				createdAt: 0,
				profilePictureURL: '',
				notFound: true,
			},
			token: '',
			role: 'EDITOR',
			name: 'Editor Token for user',
			createdAt: 1707996736,
			expiresAt: 1708169536,
			updatedAt: 1707996736,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: '',
		},
		{
			id: '7',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '',
				name: '',
				email: '',
				createdAt: 0,
				profilePictureURL: '',
				notFound: true,
			},
			token: '',
			role: 'ADMIN',
			name: 'Admin Token for user',
			createdAt: 1707996719,
			expiresAt: 0,
			updatedAt: 1707996719,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: '',
		},
		{
			id: '5',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			token: '',
			role: 'EDITOR',
			name: 'Editor Token',
			createdAt: 1707992270,
			expiresAt: 1708165070,
			updatedAt: 1707995424,
			lastUsed: 1707992517,
			revoked: false,
			updatedByUserId: 'mandalorian',
		},
	],
};

export const createAPIKeyResponse = {
	status: 'success',
	data: {
		id: '57',
		userId: 'mandalorian',
		token: '',
		name: 'test1233',
		createdAt: 1707818550,
		expiresAt: 0,
	},
};
